### ISSUE TITLE
missing convert method

### ISSUE THREAD

**Issue by johnnychen94** [JuliaArrays/OffsetArrays.jl#171]
```julia
convert(Vector, 1:5)
convert(OffsetVector, 1:5) # doesn't work
```

Will it be type piracy if we define `convert(::Type{T}, x) where {T<:OffsetArray}`?

**Comment by chriselrod** [comment]
No, because `OffsetArray` is defined here. Although defining new `convert` methods tends to cause huge numbers of invalidations.

**Comment by chriselrod** [comment]
What about something like
```julia
function Base.convert(::Type{T}, A::AbstractArray{<:Any,N}) where {T <: OffsetArray{<:Any,N}}
    OffsetArray(A, ntuple(zero, Val(N))...)
end
```
?

**Comment by jishnub** [comment]
Related to this conversion is the constructor `(::Type{<:OffsetArray})(::Array)`, which might resolve [this issue with DistributedArrays.jl](https://github.com/JuliaParallel/DistributedArrays.jl/issues/186). The offending line appears to be 
https://github.com/JuliaParallel/DistributedArrays.jl/blob/b98875d16c6810d33498405d5d852a3acee19b38/src/darray.jl#L66, where, given a type `A`, the function tries to construct an empty object of the type through 

```julia
empty_localpart(T,N,A) = A(Array{T}(undef, ntuple(zero, N)))
```

I wonder if it's worth adding the constructor as well? Although if this conversion is added, it might be possible for DistributedArrays to use that instead of the constructor, as ultimately this operation is a conversion from an `Array` to the type `A`

**Comment by jishnub** [comment]
> What about something like
> 
> ```julia
> function Base.convert(::Type{T}, A::AbstractArray{<:Any,N}) where {N, T <: OffsetArray{<:Any,N}}
>     OffsetArray(A, ntuple(zero, Val(N))...)
> end
> ```
> 
> ?

We'll perhaps need to convert or constrain the `eltype` too to avoid cases like 

```julia
julia> convert(OffsetArray{String,2}, rand(2,2))
2×2 OffsetArray(::Array{Float64,2}, 1:2, 1:2) with eltype Float64 with indices 1:2×1:2:
 0.580097  0.655686
 0.406192  0.0662347
```

**Comment by GregPlowman** [comment]
Not sure if this is the same issue, but I think I want a more narrow convert.

I would like to convert between `OffsetArrays` where the backing `AbstractArray` can be converted.
```
Base.convert(::Type{OffsetArray{T,N,A}}, x::OffsetArray{S,N}) where {T,N,A,S} = OffsetArray(convert(A, x.parent), x.offsets)
```

One scenario for this:
```
using OffsetArrays

struct Foo1
    a::Array{Float64,1}
end

struct Foo2
    o::OffsetArray{Float64,1,Array{Float64,1}}
end

A = zeros(Int, 3)
O = zeros(Int, 0:2)

Foo1(A)  # converts on construction
Foo2(O)  # errors without the extra convert method defined
```

**Comment by jishnub** [comment]
Perhaps a combination of 

```julia
julia> function Base.convert(::Type{OffsetArray{T,N,AA}}, A::AbstractArray{<:Any,N}) where {T, N, AA}
           OffsetArray{T,N,AA}(convert(AA, A)::AA, ntuple(zero, Val(N)))
       end
              
julia> function Base.convert(::Type{OffsetArray{T,N,AA}}, A::OffsetArray{<:Any,N}) where {T, N, AA}
           OffsetArray{T,N,AA}(convert(AA, A.parent)::AA, A.offsets)
       end
```

might help with conversions where all the type parameters are specified? With these, both the constructors work:

```julia
julia> Foo2(A)
Foo2([0.0, 0.0, 0.0])

julia> Foo2(O)
Foo2([0.0, 0.0, 0.0])
```

We might need other method for more general conversions such as in the top post. Not sure what's the best way to go about these.
