### ISSUE TITLE
Allow for constructing arrays with CartesianRange

### ISSUE THREAD

**Issue by AzamatB** [JuliaArrays/OffsetArrays.jl#71]
Something like
```Julia
OffsetArray{Float64}(undef, CartesianIndex(3,4,-1):CartesianIndex(7,9,5))
```

**Comment by timholy** [comment]
Good idea. PR would be welcome!

**Comment by johnnychen94** [comment]
Generally, we don't know if a given CartesianIndex array has dense indices, and we don't want to check that for such a basic construction. Hence what can be provided without loss of performance is

```julia
OffsetArray{Float64}(undef, i_first::CartesianIndex, i_last::CartesianIndex)
```

Note that this usage doesn't make sense for `Array` because Array is `1`-based.

If we support this, then we might also want to give supports to `fill!`, `fill`, `zeros`, `ones`.

**Comment by timholy** [comment]
> if a given CartesianIndex array has dense indices

It's not actually an array:

```julia
julia> R = CartesianIndex(3,4,-1):CartesianIndex(7,9,5);

julia> typeof(R)
CartesianIndices{3,Tuple{UnitRange{Int64},UnitRange{Int64},UnitRange{Int64}}}

julia> R.indices
(3:7, 4:9, -1:5)
```

So if we dispatch on `CartesianIndices` all is well.

**Comment by jishnub** [comment]
Is `R.indices` safe to use (ie. won't break)? Or should one use the roundabout `map(UnitRange, Tuple(first(R)), Tuple(last(R)) )`?

**Comment by timholy** [comment]
`R.indices` is probably OK but could also use `convert(Tuple{Vararg{AbstractUnitRange{Int}}}, iter)`.
